// src/components/shared/AppIcon.jsx
// Premium icon wrapper (lucide-react) — icon-only upgrade.
// Keeps the same positions/sizes API as the legacy Tabler `<i class="ti ti-*">`
// usage so call sites only swap the rendered icon, nothing else.
import React from 'react';
import {
  Search, Eye, EyeOff, Pencil, SquarePen, Trash2, Plus, X,
  ListFilter, SlidersHorizontal, Download, Upload, RefreshCw,
  ChevronDown, ChevronLeft, ChevronRight, Menu, Bell, Settings,
  LogOut, User, UserRound, CircleUserRound, UserCheck, Users,
  Video, VideoOff, CalendarCheck, CalendarDays, Star, ClipboardList, ClipboardCheck,
  FileText, FileSpreadsheet, FileArchive, Award, Check, Copy, Send,
  Lock, LockOpen, Mail, ArrowLeft, ArrowRight, LayoutDashboard,
  BookOpen, Library, GraduationCap, Presentation, MessageSquare,
  MessageSquareOff, Mic, MicOff, Volume2, VolumeX, Maximize, Minimize,
  Play, Square, Circle, Disc3, Info, CircleAlert, TriangleAlert,
  CircleCheck, CircleX, Ban, Power, LoaderCircle, Save, ShieldCheck,
  KeyRound, Smartphone, List, Layers, Cloud, Link, Hand, ScreenShare,
  ScreenShareOff, GitBranch, GitMerge, Armchair, ChartColumn, BadgeCheck,
  Clock, Tag, Bookmark, Printer, Share2, EllipsisVertical, House,
  CirclePlus, FileChartColumn, School, CircleGauge, Sparkles, Phone,
  Folder, ExternalLink, Undo2, CircleUser, Briefcase, Crosshair,
} from 'lucide-react';

// Legacy Tabler (`ti ti-*`) name → Lucide component.
const MAP = {
  search: Search,
  eye: Eye,
  'eye-off': EyeOff,
  pencil: Pencil,
  edit: SquarePen,
  trash: Trash2,
  plus: Plus,
  x: X,
  filter: ListFilter,
  'sliders-horizontal': SlidersHorizontal,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  menu: Menu,
  'menu-2': Menu,
  bell: Bell,
  settings: Settings,
  logout: LogOut,
  user: User,
  'user-circle': CircleUserRound,
  'user-check': UserCheck,
  users: Users,
  video: Video,
  'video-off': VideoOff,
  'calendar-check': CalendarCheck,
  'calendar-event': CalendarDays,
  star: Star,
  'star-filled': Star,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'file-analytics': FileChartColumn,
  file: FileText,
  'file-spreadsheet': FileSpreadsheet,
  'file-zip': FileArchive,
  'file-type-pdf': FileText,
  award: Award,
  certificate: BadgeCheck,
  check: Check,
  copy: Copy,
  send: Send,
  lock: Lock,
  'lock-open': LockOpen,
  'lock-check': ShieldCheck,
  mail: Mail,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrows-right': ArrowRight,
  'arrows-maximize': Maximize,
  'arrows-minimize': Minimize,
  'layout-dashboard': LayoutDashboard,
  book: BookOpen,
  books: Library,
  school: GraduationCap,
  chalkboard: Presentation,
  presentation: Presentation,
  message: MessageSquare,
  'message-off': MessageSquareOff,
  microphone: Mic,
  'microphone-off': MicOff,
  'volume-3': Volume2,
  'volume-off': VolumeX,
  'player-play': Play,
  'player-stop': Square,
  'circle-record': Disc3,
  'circle-check': CircleCheck,
  info: Info,
  'info-circle': Info,
  'alert-circle': CircleAlert,
  key: KeyRound,
  shield: ShieldCheck,
  'device-mobile': Smartphone,
  'device-floppy': Save,
  list: List,
  'stack-2': Layers,
  writing: SquarePen,
  'git-merge': GitMerge,
  armchair: Armchair,
  'chart-bar': ChartColumn,
  'chart-line': ChartColumn,
  'circle-gauge': CircleGauge,
  clock: Clock,
  tag: Tag,
  'circle-plus': CirclePlus,
  loader: LoaderCircle,
  link: Link,
  cloud: Cloud,
  hand: Hand,
  rocket: Sparkles,
  'hand-stop': Hand,
  'screen-share': ScreenShare,
  'screen-share-off': ScreenShareOff,
  'brand-github': Cloud,
  'brand-google-drive': Cloud,
  users_group: Users,
  home: House,
  bookmark: Bookmark,
  phone: Phone,
  folder: Folder,
  printer: Printer,
  share: Share2,
  dots: EllipsisVertical,
  ban: Ban,
  power: Power,
  undo: Undo2,
  circle: Circle,
  'circle-x': CircleX,
  warning: TriangleAlert,
  alert: TriangleAlert,
  'alert-triangle': TriangleAlert,
  target: Crosshair,
  layers: Layers,
  'layout-grid': LayoutDashboard,
  user_round: UserRound,
  user_circle: CircleUser,
  briefcase: Briefcase,
};

export default function AppIcon({ name, size = 16, strokeWidth = 1.9, filled = false, style = {}, className, ...rest }) {
  const Cmp = MAP[name] || Info;
  const fillOn = filled || name === 'star-filled';
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden="true"
      className={className}
      fill={fillOn ? 'currentColor' : 'none'}
      style={{ flexShrink: 0, verticalAlign: 'middle', ...style }}
      {...rest}
    />
  );
}
