// HR Candidates - search/filter/tabs/profile from /api/hr/candidates + /candidate/:id/full
import React,{useCallback,useEffect,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {card,h2,sub,page,inp,btnP,btnG,th,td,Badge,Empty,Loading,Err,fmtD} from '../../components/hr/hrUi';
import {hrGet,hrExport} from '../../features/hr/hrApi';
const TABS=[['all','All'],['eligible','Eligible'],['pipeline','In Pipeline'],['interviewing','Interviewing'],['selected','Selected'],['placed','Placed']];
export default function HRCandidates(){
const nav=useNavigate();const [sp]=useSearchParams();
const [tab,setTab]=useState(sp.get('tab')||'all');
const [search,setSearch]=useState('');const [deb,setDeb]=useState('');
const [d,setD]=useState(null);const [st,setSt]=useState('loading');const [err,setErr]=useState('');
const [sel,setSel]=useState(null);
useEffect(()=>{const t=setTimeout(()=>setDeb(search),350);return()=>clearTimeout(t);},[search]);
const load=useCallback(async()=>{setSt('loading');setErr('');try{const r=await hrGet('/candidates',{tab,search:deb,limit:25});setD(r);setSt('ok');}catch(e){setErr(e.response?.data?.message||'Unable to load.');setSt('err');}},[tab,deb]);
useEffect(()=>{load();},[load]);
const open=async(id)=>{try{const r=await hrGet('/candidate/'+id+'/full');setSel(r);}catch{}};
return(<div style={page}>
<div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',marginBottom:14}}><div><h2 style={h2}>Candidates</h2><p style={sub}>Manage placement candidates and track their progress</p></div><div style={{display:'flex',gap:8}}><button type="button" style={btnG} onClick={()=>hrExport('candidates')}>Export</button></div></div>
<div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}>{TABS.map((t)=>(<button key={t[0]} type="button" onClick={()=>setTab(t[0])} style={{...btnG,background:tab===t[0]?'#3f7da0':'#fff',color:tab===t[0]?'#fff':'#0F172A',borderColor:tab===t[0]?'#3f7da0':'#CBD5E1'}}>{t[1]} {d?.tabs?.[t[0]]??''}</button>))}</div>
<div style={{...card,marginBottom:12}}><input style={{...inp,width:'100%'}} placeholder="Search name, email, phone, skills…" value={search} onChange={(e)=>setSearch(e.target.value)}/></div>
{st==='loading'&&<Loading/>}{st==='err'&&<Err text={err} onRetry={load}/>}
{st==='ok'&&((d.candidates||[]).length===0?<Empty text="No candidates found."/>:<div style={{...card,overflowX:'auto',padding:0}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><th style={th}>Name</th><th style={th}>Batch</th><th style={th}>Skills</th><th style={th}>Stage</th><th style={th}>Score</th><th style={th}>Actions</th></tr></thead><tbody>{(d.candidates||[]).map((c)=>(<tr key={c._id}><td style={td}><b>{c.name}</b><div style={{fontSize:12,color:'#64748B'}}>{c.email}</div></td><td style={td}>{(c.batches||[]).map((b)=>b.name).join(', ')||'—'}</td><td style={td}>{(c.skills||[]).slice(0,4).join(', ')||'—'}</td><td style={td}><Badge v={c.placementStatus}/></td><td style={td}>{c.score??'—'}</td><td style={td}><div style={{display:'flex',gap:6}}><button type="button" style={btnG} onClick={()=>open(c._id)}>Profile</button><button type="button" style={btnG} onClick={()=>nav('/hr/interviews?candidate='+c._id)}>Interview</button></div></td></tr>))}</tbody></table></div>)}
{sel&&(<div style={{...card,marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{margin:0}}>Profile · {sel.candidate?.name}</h3><button type="button" style={btnG} onClick={()=>setSel(null)}>Close</button></div><p style={sub}>{sel.candidate?.email} · <Badge v={sel.candidate?.placementStatus}/></p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12,marginTop:12}}><div><b>Overview</b><div style={{fontSize:13}}>Phone: {sel.candidate?.phone||'—'}<br/>Skills: {(sel.candidate?.skills||[]).join(', ')||'—'}<br/>Company: {sel.candidate?.companyName||'—'} · CTC: {sel.candidate?.ctc||'—'}</div></div><div><b>Learning (read-only)</b><div style={{fontSize:13}}>Attendance: {sel.learning?.attendance?.present??0}/{sel.learning?.attendance?.total??0}<br/>Certificates: {(sel.learning?.certificates||[]).length}<br/>Enrollments: {(sel.learning?.enrollments||[]).map((e)=>e.course).join(', ')||'—'}</div></div><div><b>Interviews ({(sel.interviews||[]).length})</b>{(sel.interviews||[]).slice(0,5).map((i)=>(<div key={i._id} style={{fontSize:12}}>{fmtD(i.scheduledAt)} · {i.company?.name||''} · {i.status}</div>))}</div><div><b>Offers ({(sel.offers||[]).length}) · Placements ({(sel.placements||[]).length})</b>{(sel.offers||[]).slice(0,5).map((o)=>(<div key={o._id} style={{fontSize:12}}>{o.company?.name||''} · {o.ctc||''} · {o.status}</div>))}{(sel.placements||[]).slice(0,5).map((p)=>(<div key={p._id} style={{fontSize:12}}>Placed: {p.company?.name||''} · {p.status}</div>))}</div></div><div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button type="button" style={btnP} onClick={()=>nav('/hr/interviews?candidate='+sel.candidate._id)}>Schedule Interview</button><button type="button" style={btnG} onClick={()=>nav('/hr/offers?search='+encodeURIComponent(sel.candidate.email))}>View Offers</button><button type="button" style={btnG} onClick={()=>nav('/hr/placements?search='+encodeURIComponent(sel.candidate.email))}>View Placement</button></div></div>)}
</div>);}
